### ISSUE TITLE
bug fix suggestion

### ISSUE THREAD

**Issue by sngyai** [jsxc/strophe.jinglejs#3]
Sorry, but you should modify [JingleSession start](https://github.com/jsxc/strophe.jinglejs/blob/master/strophe.jinglejs-bundle.js#L7048) and add a random "id" attribute to it, otherwise ejabberd17.03 would response a bad-request: Missing attribute "id", as a result of ejabberd has been refactored since 17.01

**Comment by sualko** [comment]
The file has bundle in his name for a reason. You should report this to the depending lib: https://github.com/otalk/jingle-session/blob/master/index.js#L202 and please mention this issue, so that I can keep track of it. Thanks for reporting anyway.

**Comment by sngyai** [comment]
Thank you all the same.

**Comment by smassonnat** [comment]
I link here the issue reported by @sngyai regarding this : https://github.com/otalk/jingle-session/issues/5.
As it was solved, you might want to update the dependency

**Comment by sualko** [comment]
@smassonnat thanks for the remainder. I updated all dependencies, but I had no time to test. I will create a new release if I had.
